package Status;

public enum StatusType {
	ACCURACY_STATUS,
    BLEED_STATUS,
    BLIND_STATUS,
    DAZE_STATUS,
    DRAIN_STATUS,
    ECHO_OF_ETERNITY_STATUS,
    ETHEREAL_CHAINS_STATUS,
    FEAR_STATUS,
    FIRE_STATUS,
    ICE_STATUS,
    ILLUSORY_DOUBLE_STATUS,
    LIFE_STEAL_STATUS,
    MIND_PROBE_STATUS,
    POISON_STATUS,
    RADIANT_STATUS,
    REDUCE_DEFENSE_STATUS,
    REDUCE_STRENGTH_STATUS,
    // Add more as needed
}
