package Status;

public enum StatusType {
    BlEEDSTATUS,
    BLINDSTATUS,
    DAZESTATUS,
    DRAINSTATUS,
    ECHOOFETERNITYSTATUS,
    ETHEREALCHAINSSTATUS,
    FEARSTATUS,
    FIRESTATUS,
    ICESTATUS,
    ILLUSORYDOUBLESTATUS,
    LIFESTEALSTATUS,
    MINDPROBESTATUS,
    POISONSTATUS,
    RADIANTSTATUS,
    REDUCEDEFENSESTATUS,
    REDUCESTRENGTHSTATUS,
    // Add more as needed
}