package SharedData;

public enum Guild {
    AURORA_ARCNUM,
    CELESTIAL_ARCANE_ORDER,
    CRIMSON_BLADES,
    CRIMSON_VEIL_ROGUES,
    DAWNWARD_PALADINS,
    DIRGEWEAVERS_CHORUS,
    HARMONILIC_LIGHT_ENSEMBLE,
    NIGHT_SHADE_HUNTERS,
    OBSIDIAN_HEX_COVEN,
    OBSIDIAN_SHADOW_SYNDICATE,
    SILVERWARD_SENTINELS,
    NON_GUILD
}